/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.Graphics;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.UIManager;

/**
 *
 * @author asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xMouse,yMouse;
    public Login() {
        initComponents();
    }
class gradientJPanel extends JPanel{
    protected void paintComponent(Graphics q){
        Graphics2D g2d =(Graphics2D) q;
        int w = getWidth();
        int h = getHeight();
        
        Color c1 = new Color (171, 227, 226);
        Color c2 = new Color (67, 151, 164);
        GradientPaint gp = new GradientPaint(0,0, c1, 180,h, c2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h );
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Design = new gradientJPanel();
        icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Table_form = new javax.swing.JPanel();
        bg_btn = new javax.swing.JPanel();
        btn_daftar = new javax.swing.JPanel();
        daftart = new javax.swing.JLabel();
        btn_masuk = new javax.swing.JPanel();
        masuk = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        txt_email = new com.source.design.textfield();
        password = new javax.swing.JLabel();
        txt_password = new com.source.design.textfield();
        Btn_masuk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close1 = new com.source.button.close();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1381, 810));
        setMinimumSize(new java.awt.Dimension(1381, 810));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1381, 810));
        setSize(new java.awt.Dimension(1381, 810));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Design.setBackground(new java.awt.Color(0, 153, 153));
        Design.setPreferredSize(new java.awt.Dimension(685, 830));
        Design.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/img/Illustration.png"))); // NOI18N
        Design.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat Datang");
        Design.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KOSANKU");
        Design.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));

        Table_form.setBackground(new java.awt.Color(255, 255, 255));
        Table_form.setPreferredSize(new java.awt.Dimension(620, 750));

        bg_btn.setBackground(new java.awt.Color(67, 151, 164));
        bg_btn.setForeground(new java.awt.Color(67, 151, 164));
        bg_btn.setPreferredSize(new java.awt.Dimension(620, 55));

        btn_daftar.setBackground(new java.awt.Color(67, 151, 164));
        btn_daftar.setToolTipText("");
        btn_daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_daftar.setPreferredSize(new java.awt.Dimension(310, 55));
        btn_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_daftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_daftarMouseExited(evt);
            }
        });
        btn_daftar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftart.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        daftart.setForeground(new java.awt.Color(255, 255, 255));
        daftart.setText("DAFTAR");
        btn_daftar.add(daftart, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 3, -1, 50));

        btn_masuk.setBackground(new java.awt.Color(54, 138, 151));
        btn_masuk.setToolTipText("");
        btn_masuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_masuk.setPreferredSize(new java.awt.Dimension(310, 55));
        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_masukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_masukMouseExited(evt);
            }
        });
        btn_masuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masuk.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        masuk.setForeground(new java.awt.Color(255, 255, 255));
        masuk.setText("MASUK");
        btn_masuk.add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 3, -1, 50));

        javax.swing.GroupLayout bg_btnLayout = new javax.swing.GroupLayout(bg_btn);
        bg_btn.setLayout(bg_btnLayout);
        bg_btnLayout.setHorizontalGroup(
            bg_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_btnLayout.createSequentialGroup()
                .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bg_btnLayout.setVerticalGroup(
            bg_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_btnLayout.createSequentialGroup()
                .addGroup(bg_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form.setBackground(new java.awt.Color(255, 255, 255));

        email.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(67, 151, 164));
        email.setText("Email");

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(null);
        txt_email.setForeground(new java.awt.Color(67, 151, 164));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        password.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(67, 151, 164));
        password.setText("Password");

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setBorder(null);
        txt_password.setForeground(new java.awt.Color(67, 151, 164));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Btn_masuk.setBackground(new java.awt.Color(67, 151, 164));
        Btn_masuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_masuk.setMaximumSize(new java.awt.Dimension(137, 54));
        Btn_masuk.setMinimumSize(new java.awt.Dimension(137, 54));
        Btn_masuk.setPreferredSize(new java.awt.Dimension(137, 54));
        Btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_masukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_masukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_masukMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASUK");

        javax.swing.GroupLayout Btn_masukLayout = new javax.swing.GroupLayout(Btn_masuk);
        Btn_masuk.setLayout(Btn_masukLayout);
        Btn_masukLayout.setHorizontalGroup(
            Btn_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
            .addGroup(Btn_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Btn_masukLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Btn_masukLayout.setVerticalGroup(
            Btn_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
            .addGroup(Btn_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Btn_masukLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addComponent(Btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Table_formLayout = new javax.swing.GroupLayout(Table_form);
        Table_form.setLayout(Table_formLayout);
        Table_formLayout.setHorizontalGroup(
            Table_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Table_formLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        Table_formLayout.setVerticalGroup(
            Table_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Table_formLayout.createSequentialGroup()
                .addComponent(bg_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Design, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Table_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Table_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_daftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseEntered
        btn_daftar.setBackground(new Color(54,  138,  151));
    }//GEN-LAST:event_btn_daftarMouseEntered

    private void btn_daftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseExited
        btn_daftar.setBackground(new Color(67, 151, 164));
    }//GEN-LAST:event_btn_daftarMouseExited

    private void btn_masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseEntered
        btn_masuk.setBackground(new Color(42,  126,  139));
    }//GEN-LAST:event_btn_masukMouseEntered

    private void btn_masukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseExited
        btn_masuk.setBackground(new Color(54,  138,  151));
    }//GEN-LAST:event_btn_masukMouseExited

    private void btn_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseClicked
        this.setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_btn_daftarMouseClicked

    private void Btn_masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_masukMouseEntered
        Btn_masuk.setBackground(new Color(54,  138,  151)); 
    }//GEN-LAST:event_Btn_masukMouseEntered

    private void Btn_masukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_masukMouseExited
        Btn_masuk.setBackground(new Color(67, 151, 164));
    }//GEN-LAST:event_Btn_masukMouseExited

    private void Btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_masukMouseClicked
        try{
            String sql= "SELECT * FROM profil WHERE email='"+txt_email.getText()+ "'AND password='"+ txt_password.getText()+"'";
            Connection con=(Connection)Koneksi.koneksiDB();
            PreparedStatement pst= con.prepareStatement(sql);
            ResultSet rs= pst.executeQuery(sql);
            if (rs.next()){
               if (txt_email.getText().equals(rs.getString("email"))
                       && txt_password.getText().equals(rs.getString("password"))) {
                   JOptionPane.showMessageDialog(null, " Berhasil Login");
                   this.setVisible(false);
                   new Menu().setVisible(true);
               }
            } 
            else {
                JOptionPane.showMessageDialog(null, "Email atau password salah");
            }
            
        }
            catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_Btn_masukMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf() {
            });
        } catch (Exception e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Btn_masuk;
    private javax.swing.JPanel Design;
    private javax.swing.JPanel Table_form;
    private javax.swing.JPanel bg_btn;
    private javax.swing.JPanel btn_daftar;
    private javax.swing.JPanel btn_masuk;
    private com.source.button.close close1;
    private javax.swing.JLabel daftart;
    private javax.swing.JLabel email;
    private javax.swing.JPanel form;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel masuk;
    private javax.swing.JLabel password;
    private com.source.design.textfield txt_email;
    private com.source.design.textfield txt_password;
    // End of variables declaration//GEN-END:variables
}
