
package com.main;


import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class Menu extends javax.swing.JFrame {
int xMouse,yMouse;
    public Menu() {
        initComponents();
        loadData();
        resetautoincrement();
        Totalmasuk();
        total();
    }

    
    private void total(){
        try {
            String sql = "SELECT COUNT(tanggal_bayar)\n" +
                            "FROM client\n" +
                            "WHERE NOW()>tanggal_bayar";
            String sql1 = "SELECT COUNT(id_client) AS totalorg FROM client";
            Connection con = (Connection)Koneksi.koneksiDB();
            Statement stm = con.createStatement();
            Statement stm1 = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            ResultSet rs1 = stm1.executeQuery(sql1);
            while (rs.next()&&rs1.next()){
                totaltelat.setText(rs.getString(1));
                totalorang.setText(rs1.getString(1));
            }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Load Data\n"+e.getMessage());
        }
    }
    
    private void Totalmasuk(){
 int t=0;
        
        try {
            String sql = "SELECT SUM(nominal) FROM pemasukan" ;
            
            Connection con          = (Connection)Koneksi.koneksiDB();
            PreparedStatement pst   = con.prepareStatement(sql);
            ResultSet rs            = pst.executeQuery(sql);
            
            if(rs.next()){
                total.setText(rs.getString(1));
            }
            
        } catch (Exception e) {
            System.out.println("Error");
            e.printStackTrace();
        }
    }
    
    
    private void resetautoincrement(){
        try {
            String sql1 = "ALTER TABLE profil AUTO_INCREMENT=1";
            String sql2 = "ALTER TABLE rumah_kost AUTO_INCREMENT=1";
            String sql3 = "ALTER TABLE kamar AUTO_INCREMENT=1";
            String sql4 = "ALTER TABLE client AUTO_INCREMENT=1";
            String sql5 = "ALTER TABLE pemasukan AUTO_INCREMENT=1";
            String sql6 = "ALTER TABLE pengeluaran AUTO_INCREMENT=1";
            
            Connection con = (Connection)Koneksi.koneksiDB();
            PreparedStatement pst1 = con.prepareStatement(sql1);
            PreparedStatement pst2 = con.prepareStatement(sql2);
            PreparedStatement pst3 = con.prepareStatement(sql3);
            PreparedStatement pst4 = con.prepareStatement(sql4);
            PreparedStatement pst5 = con.prepareStatement(sql5);
            PreparedStatement pst6 = con.prepareStatement(sql6);
            pst1.execute();
            pst2.execute();
            pst3.execute();
            pst4.execute();
            pst5.execute();
            pst6.execute();
            
            
        } 
        catch (Exception e) {
        }
    }
    
    private void loadData(){
        try {
            String sql = "select * from profil";
            Connection con = (Connection)Koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
        while (res.next()){
            txt_nama.setText(res.getString("username"));
            txt_email.setText(res.getString("email"));
            txt_nomor.setText(res.getString("nohp"));
            txt_password.setText(res.getString("password"));
            txt_id.setText(res.getString("id_pemilik"));
        }    
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        biodata = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        txt_nama = new com.source.design.textfield2();
        email = new javax.swing.JLabel();
        txt_email = new com.source.design.textfield2();
        nomor = new javax.swing.JLabel();
        txt_nomor = new com.source.design.textfield2();
        password = new javax.swing.JLabel();
        txt_password = new com.source.design.textfield2();
        password1 = new javax.swing.JLabel();
        txt_id = new com.source.design.textfield2();
        btn_logout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_rmk = new javax.swing.JPanel();
        icon_rmk = new javax.swing.JLabel();
        rmk = new javax.swing.JLabel();
        btn_client = new javax.swing.JPanel();
        icon_rmk1 = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        btn_kelola = new javax.swing.JPanel();
        icon_rmk2 = new javax.swing.JLabel();
        rmk2 = new javax.swing.JLabel();
        btn_statistik = new javax.swing.JPanel();
        icon_rmk3 = new javax.swing.JLabel();
        rmk3 = new javax.swing.JLabel();
        total_pemasukan = new javax.swing.JPanel();
        totalPemasukan = new javax.swing.JLabel();
        totalPemasukan1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        TelatMembayar1 = new javax.swing.JPanel();
        jumlah1 = new javax.swing.JLabel();
        org1 = new javax.swing.JLabel();
        totalorang = new javax.swing.JLabel();
        TelatMembayar = new javax.swing.JPanel();
        jumlah = new javax.swing.JLabel();
        org = new javax.swing.JLabel();
        totaltelat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 810));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(1381, 810));
        bg.setMinimumSize(new java.awt.Dimension(1381, 810));
        bg.setPreferredSize(new java.awt.Dimension(1381, 810));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(67, 151, 164));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("KOSANKU");
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 5, -1, 50));

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 270, 50));

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 151, 164));
        jLabel1.setText("EXIT");
        btn_exit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 12, -1, -1));

        bg.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 120, 40));

        biodata.setBackground(new java.awt.Color(67, 151, 164));
        biodata.setMaximumSize(new java.awt.Dimension(395, 555));
        biodata.setMinimumSize(new java.awt.Dimension(395, 555));
        biodata.setPreferredSize(new java.awt.Dimension(395, 555));
        biodata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selamat datang");
        biodata.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 123, -1));

        nama.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama  ");
        biodata.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txt_nama.setEditable(false);
        txt_nama.setBackground(new java.awt.Color(67, 151, 164));
        txt_nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        biodata.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 270, -1));

        email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email ");
        biodata.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txt_email.setEditable(false);
        txt_email.setBackground(new java.awt.Color(67, 151, 164));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        biodata.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 270, -1));

        nomor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nomor.setForeground(new java.awt.Color(255, 255, 255));
        nomor.setText("Nomor  ");
        biodata.add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txt_nomor.setEditable(false);
        txt_nomor.setBackground(new java.awt.Color(67, 151, 164));
        txt_nomor.setForeground(new java.awt.Color(255, 255, 255));
        txt_nomor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        biodata.add(txt_nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 270, -1));

        password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password ");
        biodata.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        txt_password.setEditable(false);
        txt_password.setBackground(new java.awt.Color(67, 151, 164));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        biodata.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 270, -1));

        password1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 255, 255));
        password1.setText("ID Pemilik");
        biodata.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(67, 151, 164));
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        biodata.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 270, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 151, 164));
        jLabel4.setText("LOG OUT");
        btn_logout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 12, -1, -1));

        biodata.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/img/Avatars.png"))); // NOI18N
        jLabel3.setLabelFor(biodata);
        biodata.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -40, 170, 240));

        bg.add(biodata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        btn_rmk.setBackground(new java.awt.Color(67, 151, 164));
        btn_rmk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rmkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_rmkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_rmkMouseExited(evt);
            }
        });
        btn_rmk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_rmk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_rmk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/img/Home Apps.png"))); // NOI18N
        icon_rmk.setLabelFor(btn_rmk);
        icon_rmk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icon_rmk.setDoubleBuffered(true);
        icon_rmk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_rmk.add(icon_rmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        rmk.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        rmk.setForeground(new java.awt.Color(255, 255, 255));
        rmk.setText("Rumah Kost");
        btn_rmk.add(rmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        bg.add(btn_rmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 240, 220));

        btn_client.setBackground(new java.awt.Color(67, 151, 164));
        btn_client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clientMouseExited(evt);
            }
        });
        btn_client.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_rmk1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_rmk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/img/Home Check.png"))); // NOI18N
        icon_rmk1.setLabelFor(btn_rmk);
        icon_rmk1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icon_rmk1.setDoubleBuffered(true);
        icon_rmk1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_client.add(icon_rmk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        client.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        client.setForeground(new java.awt.Color(255, 255, 255));
        client.setText("Client");
        btn_client.add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        bg.add(btn_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 240, 220));

        btn_kelola.setBackground(new java.awt.Color(67, 151, 164));
        btn_kelola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kelola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kelolaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kelolaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kelolaMouseExited(evt);
            }
        });
        btn_kelola.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_rmk2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_rmk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/img/Home Add.png"))); // NOI18N
        icon_rmk2.setLabelFor(btn_rmk);
        icon_rmk2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icon_rmk2.setDoubleBuffered(true);
        icon_rmk2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_kelola.add(icon_rmk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        rmk2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        rmk2.setForeground(new java.awt.Color(255, 255, 255));
        rmk2.setText("Kelola");
        btn_kelola.add(rmk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        bg.add(btn_kelola, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 240, 220));

        btn_statistik.setBackground(new java.awt.Color(67, 151, 164));
        btn_statistik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_statistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_statistikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_statistikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_statistikMouseExited(evt);
            }
        });
        btn_statistik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_rmk3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_rmk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/img/Home Info.png"))); // NOI18N
        icon_rmk3.setLabelFor(btn_rmk);
        icon_rmk3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icon_rmk3.setDoubleBuffered(true);
        icon_rmk3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_statistik.add(icon_rmk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        rmk3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        rmk3.setForeground(new java.awt.Color(255, 255, 255));
        rmk3.setText("Laporan");
        btn_statistik.add(rmk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        bg.add(btn_statistik, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 240, 220));

        total_pemasukan.setBackground(new java.awt.Color(67, 151, 164));

        totalPemasukan.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        totalPemasukan.setForeground(new java.awt.Color(255, 255, 255));
        totalPemasukan.setText("Total pemasukan");

        totalPemasukan1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        totalPemasukan1.setForeground(new java.awt.Color(255, 255, 255));
        totalPemasukan1.setText("Rp");

        total.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout total_pemasukanLayout = new javax.swing.GroupLayout(total_pemasukan);
        total_pemasukan.setLayout(total_pemasukanLayout);
        total_pemasukanLayout.setHorizontalGroup(
            total_pemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(total_pemasukanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(total_pemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPemasukan)
                    .addGroup(total_pemasukanLayout.createSequentialGroup()
                        .addComponent(totalPemasukan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 56, Short.MAX_VALUE))
        );
        total_pemasukanLayout.setVerticalGroup(
            total_pemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(total_pemasukanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(total_pemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPemasukan1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        bg.add(total_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 240, 80));

        TelatMembayar1.setBackground(new java.awt.Color(67, 151, 164));

        jumlah1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jumlah1.setForeground(new java.awt.Color(255, 255, 255));
        jumlah1.setText("Total Penghuni");

        org1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        org1.setForeground(new java.awt.Color(255, 255, 255));
        org1.setText("Orang");

        totalorang.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        totalorang.setForeground(new java.awt.Color(255, 255, 255));
        totalorang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout TelatMembayar1Layout = new javax.swing.GroupLayout(TelatMembayar1);
        TelatMembayar1.setLayout(TelatMembayar1Layout);
        TelatMembayar1Layout.setHorizontalGroup(
            TelatMembayar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelatMembayar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelatMembayar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah1)
                    .addGroup(TelatMembayar1Layout.createSequentialGroup()
                        .addComponent(totalorang, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(org1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelatMembayar1Layout.setVerticalGroup(
            TelatMembayar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelatMembayar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelatMembayar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalorang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(org1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(TelatMembayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, 150, 80));

        TelatMembayar.setBackground(new java.awt.Color(67, 151, 164));

        jumlah.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setText("Telat Membayar");

        org.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        org.setForeground(new java.awt.Color(255, 255, 255));
        org.setText("Orang");

        totaltelat.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        totaltelat.setForeground(new java.awt.Color(255, 255, 255));
        totaltelat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout TelatMembayarLayout = new javax.swing.GroupLayout(TelatMembayar);
        TelatMembayar.setLayout(TelatMembayarLayout);
        TelatMembayarLayout.setHorizontalGroup(
            TelatMembayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelatMembayarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelatMembayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah)
                    .addGroup(TelatMembayarLayout.createSequentialGroup()
                        .addComponent(totaltelat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(org)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelatMembayarLayout.setVerticalGroup(
            TelatMembayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelatMembayarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelatMembayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totaltelat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(org, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(TelatMembayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 150, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        btn_exit.setBackground(new Color(209,  209,  209));
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        btn_exit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
       btn_logout.setBackground(new Color(209,  209,  209));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        btn_logout.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_rmkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rmkMouseEntered
        btn_rmk.setBackground(new Color(54,  138,  151));
    }//GEN-LAST:event_btn_rmkMouseEntered

    private void btn_rmkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rmkMouseExited
        btn_rmk.setBackground(new Color(67, 151, 164));
    }//GEN-LAST:event_btn_rmkMouseExited

    private void btn_rmkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rmkMouseClicked
        this.setVisible(false);
        new RumahKost().setVisible(true);
    }//GEN-LAST:event_btn_rmkMouseClicked

    private void btn_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientMouseClicked
        this.setVisible(false);
        new Client().setVisible(true);
    }//GEN-LAST:event_btn_clientMouseClicked

    private void btn_clientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientMouseEntered
        btn_client.setBackground(new Color(54,  138,  151));
    }//GEN-LAST:event_btn_clientMouseEntered

    private void btn_clientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientMouseExited
        btn_client.setBackground(new Color(67, 151, 164));
    }//GEN-LAST:event_btn_clientMouseExited

    private void btn_kelolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelolaMouseClicked
        this.setVisible(false);
        new Kelola().setVisible(true);
    }//GEN-LAST:event_btn_kelolaMouseClicked

    private void btn_kelolaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelolaMouseEntered
        btn_kelola.setBackground(new Color(54,  138,  151));
    }//GEN-LAST:event_btn_kelolaMouseEntered

    private void btn_kelolaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelolaMouseExited
       btn_kelola.setBackground(new Color(67, 151, 164));
    }//GEN-LAST:event_btn_kelolaMouseExited

    private void btn_statistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseClicked
        this.setVisible(false);
        new Statistik().setVisible(true);
    }//GEN-LAST:event_btn_statistikMouseClicked

    private void btn_statistikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseEntered
        btn_statistik.setBackground(new Color(54,  138,  151));
    }//GEN-LAST:event_btn_statistikMouseEntered

    private void btn_statistikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseExited
        btn_statistik.setBackground(new Color(67, 151, 164));
    }//GEN-LAST:event_btn_statistikMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            UIManager.setLookAndFeel(new FlatDarkLaf() {
            });
        } catch (Exception e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelatMembayar;
    private javax.swing.JPanel TelatMembayar1;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel biodata;
    private javax.swing.JPanel btn_client;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_kelola;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_rmk;
    private javax.swing.JPanel btn_statistik;
    private javax.swing.JLabel client;
    private javax.swing.JLabel email;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icon_rmk;
    private javax.swing.JLabel icon_rmk1;
    private javax.swing.JLabel icon_rmk2;
    private javax.swing.JLabel icon_rmk3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel jumlah1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nomor;
    private javax.swing.JLabel org;
    private javax.swing.JLabel org1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel rmk;
    private javax.swing.JLabel rmk2;
    private javax.swing.JLabel rmk3;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalPemasukan;
    private javax.swing.JLabel totalPemasukan1;
    private javax.swing.JPanel total_pemasukan;
    private javax.swing.JLabel totalorang;
    private javax.swing.JLabel totaltelat;
    private com.source.design.textfield2 txt_email;
    private com.source.design.textfield2 txt_id;
    private com.source.design.textfield2 txt_nama;
    private com.source.design.textfield2 txt_nomor;
    private com.source.design.textfield2 txt_password;
    // End of variables declaration//GEN-END:variables
}
